/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosistemavehicular.Presentacion;

import com.mycompany.proyectosistemavehicular.Logica.LogPropietario;
import com.mycompany.proyectosistemavehicular.Logica.LogTurno;
import com.mycompany.proyectosistemavehicular.Logica.LogVehiculo;
import com.mycompany.proyectosistemavehicular.clases.EstadoVehiculo;
import com.mycompany.proyectosistemavehicular.clases.Propietario;
import com.mycompany.proyectosistemavehicular.clases.Turno;
import com.mycompany.proyectosistemavehicular.clases.Vehiculo;
import java.util.Date;
import javax.swing.JOptionPane;
import percistencias.VehiculoJpaController;

/**
 *
 * @author vcarl
 */
public class ReservaTurnos extends javax.swing.JFrame {

    /**
     * Creates new form ReservaTurnos
     */
    public ReservaTurnos() {
        initComponents();
    }

    public Vehiculo buscarVehiculoSeleccionado() {
        int idVehi = Integer.parseInt(TXT_IdVehiculo.getText());
        VehiculoJpaController jpa = new VehiculoJpaController();
        return jpa.findVehiculo(idVehi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTN_Registrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXT_Cedula = new javax.swing.JTextField();
        TXT_IdVehiculo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXT_Anden = new javax.swing.JTextField();
        CBX_Dia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        CBX_Mes = new javax.swing.JComboBox<>();
        CBX_Hora = new javax.swing.JComboBox<>();
        BTN_CedulaConfirmacion = new javax.swing.JButton();
        BTN_IdConfirmacion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_Registrar.setText("Registrar");
        BTN_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RegistrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Registrar Vehiculo");

        jLabel6.setText("Ingrese el id del vehiculo: ");

        jLabel7.setText("Ingrese su cedula: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Horario del prestamo");

        jLabel3.setText("Anden:");

        jLabel4.setText("Dia:");

        jLabel8.setText("Hora:");

        TXT_Anden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_AndenActionPerformed(evt);
            }
        });

        CBX_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel9.setText("Mes:");

        CBX_Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        CBX_Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00" }));

        BTN_CedulaConfirmacion.setText("-");
        BTN_CedulaConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CedulaConfirmacionActionPerformed(evt);
            }
        });

        BTN_IdConfirmacion.setText("-");
        BTN_IdConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_IdConfirmacionActionPerformed(evt);
            }
        });

        jButton2.setText("Menù");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Cedula)
                            .addComponent(TXT_IdVehiculo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(TXT_Anden))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CBX_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBX_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CBX_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_CedulaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_IdConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(BTN_Registrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_CedulaConfirmacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXT_IdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_IdConfirmacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBX_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(CBX_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBX_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_Anden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_Registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_AndenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_AndenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_AndenActionPerformed

    private void BTN_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RegistrarActionPerformed
        try {
            // 1. Obtener datos del formulario
            String dia = CBX_Dia.getSelectedItem().toString();
            String mes = CBX_Mes.getSelectedItem().toString();
            String hora = CBX_Hora.getSelectedItem().toString();
            String anden = TXT_Anden.getText().trim();

            // Validar campos básicos
            if (dia.isEmpty() || mes.isEmpty() || hora.isEmpty() || anden.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
                return;
            }

            // 2. Crear la fecha del turno (día del turno)
            int anioActual = java.time.Year.now().getValue();
            String fechaTexto = anioActual + "-" + mes + "-" + dia;

            // Convertir a java.util.Date
            java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("yyyy-MM-dd");
            Date fechaTurno = formato.parse(fechaTexto);

            // 3. Buscar el vehículo 
            Vehiculo vehiculo = buscarVehiculoSeleccionado();

            if (vehiculo == null) {
                JOptionPane.showMessageDialog(this, "Vehículo no válido o no seleccionado.");
                return;
            }

            // 4. Validar si ya tiene un turno ese día o en ese andén
            LogTurno log = new LogTurno();
            if (!log.validarTurno(vehiculo, fechaTurno, anden)) {
                JOptionPane.showMessageDialog(this, "Este vehículo ya tiene un turno ese día o en ese andén.");
                return;
            }

            // 5. Crear el turno
            Turno turno = new Turno();
            turno.setAnden(anden);
            turno.setHoraTurno(hora);
            turno.setDiaTurno(fechaTurno);
            turno.setFechaCreacion(new Date()); // ahora
            turno.setVehiculo(vehiculo);

            // 6. Guardar el turno
            log.insertarTurno(turno);

            // 7. Cambiar estado del vehículo
            vehiculo.setEstado(EstadoVehiculo.EN_USO);
            new VehiculoJpaController().edit(vehiculo);

            JOptionPane.showMessageDialog(this, "Turno registrado exitosamente.");
            TXT_Anden.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar turno: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BTN_RegistrarActionPerformed

    private void BTN_CedulaConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CedulaConfirmacionActionPerformed
        LogPropietario log = new LogPropietario();
        Propietario p = log.buscarPropietarioPorCedula(TXT_Cedula.getText().trim());
        if (p == null) {
            JOptionPane.showMessageDialog(this, "No existe propietario con esa cédula.");
            BTN_CedulaConfirmacion.setText("❌");
            return;
        }else{
            BTN_CedulaConfirmacion.setText("✅");
        }
    }//GEN-LAST:event_BTN_CedulaConfirmacionActionPerformed

    private void BTN_IdConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_IdConfirmacionActionPerformed
        LogVehiculo log = new LogVehiculo();
        int id = Integer.parseInt(TXT_IdVehiculo.getText().trim());
        Vehiculo p = log.buscarVehiculoPorId(id);
        if (p == null) {
            JOptionPane.showMessageDialog(this, "No existe vehiculo con ese id.");
            BTN_CedulaConfirmacion.setText("❌");
            return;
        }else{
            BTN_CedulaConfirmacion.setText("✅");
        }
    }//GEN-LAST:event_BTN_IdConfirmacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new VentanaPrincipal().setVisible(true);
        this.dispose(); // Cierra la ventana actual
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaTurnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CedulaConfirmacion;
    private javax.swing.JButton BTN_IdConfirmacion;
    private javax.swing.JButton BTN_Registrar;
    private javax.swing.JComboBox<String> CBX_Dia;
    private javax.swing.JComboBox<String> CBX_Hora;
    private javax.swing.JComboBox<String> CBX_Mes;
    private javax.swing.JTextField TXT_Anden;
    private javax.swing.JTextField TXT_Cedula;
    private javax.swing.JTextField TXT_IdVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
